; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = DEV_nano33ble

[common]
framework = arduino
lib_deps = 
	adafruit/Adafruit MPRLS Library@^1.2.2	
	adafruit/Adafruit NeoPixel@^1.15.4
build_flags =
	-D PCB_REVISION=0


[env:DEV_nano33ble]
extends = common
platform = nordicnrf52
board = nano33ble
build_flags =
	${common.build_flags}
	-D CAN_STORE_MANY_STRINGS=1
	-D VERSION_DEV=1
	-D SERIALBAUD=115200
build_type = debug

[env:RELEASE_nano33ble]
extends = common
platform = nordicnrf52
board = nano33ble
build_flags =
	${common.build_flags}
	-D CAN_STORE_MANY_STRINGS=1
	-D SERIALBAUD=115200
build_type = release

[env:RELEASE_nanoatmega328]
extends = common
platform = atmelavr
board = nanoatmega328
build_flags = 
	${common.build_flags}
	-D SERIALBAUD=9600
build_type = release
